services:
  pdfsemanticsearchdemo:
    image: ${DOCKER_REGISTRY-}pdfsemanticsearchdemo
    build:
      context: .
      dockerfile: PdfSemanticSearchDemo/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - OLLAMA_API_URL=http://ollama:11434
      - QDRANT_API_URL=qdrant
    depends_on:
      - qdrant
      - ollama
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage  # Persistent volume for Qdrant
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama  # persists models and configs
    restart: unless-stopped
    tty: true  # needed for some models
    environment:
      - OLLAMA_MODELS=/root/.ollama
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 2 && ollama pull nomic-embed-text && ollama pull llama3.2 && wait"]

volumes:
  ollama_data:
  qdrant_data:

